// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUTplWuAgfetvKfw3lblBDLHEi29hTvTY',
    appId: '1:329308170158:web:ccd88b58ff957ac04f4a3f',
    messagingSenderId: '329308170158',
    projectId: 'maymuna-collection',
    authDomain: 'maymuna-collection.firebaseapp.com',
    storageBucket: 'maymuna-collection.appspot.com',
    measurementId: 'G-SQJFN3PQC6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWgzJvIWtE6idKUOCZM7JyPluJoqrckVw',
    appId: '1:329308170158:android:37ea70da2fcdf93d4f4a3f',
    messagingSenderId: '329308170158',
    projectId: 'maymuna-collection',
    storageBucket: 'maymuna-collection.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz0sT7jBaCg7E0MezgJ6jgYgi7nUnESVY',
    appId: '1:329308170158:ios:8ce25d89d49c1daf4f4a3f',
    messagingSenderId: '329308170158',
    projectId: 'maymuna-collection',
    storageBucket: 'maymuna-collection.appspot.com',
    androidClientId: '329308170158-u3a3q96qk92e2tb8lhcfd0u8k1hm979r.apps.googleusercontent.com',
    iosClientId: '329308170158-0egpq9ktbki9jgsr1g4l64p4isnqm0gs.apps.googleusercontent.com',
    iosBundleId: 'com.example.maymunaAdminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz0sT7jBaCg7E0MezgJ6jgYgi7nUnESVY',
    appId: '1:329308170158:ios:a0c73f5943cda8724f4a3f',
    messagingSenderId: '329308170158',
    projectId: 'maymuna-collection',
    storageBucket: 'maymuna-collection.appspot.com',
    androidClientId: '329308170158-u3a3q96qk92e2tb8lhcfd0u8k1hm979r.apps.googleusercontent.com',
    iosClientId: '329308170158-fsj5bvl760d3f921u07sl97h2jj200it.apps.googleusercontent.com',
    iosBundleId: 'com.example.maymunaAdminPanel.RunnerTests',
  );
}
